### ISSUE TITLE
SIGWINCH is reported as "debug event-> 28"

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#207]
I've spent quite some time trying to figure out what on earth such a message from EDB means. After digging through the sources, I discovered that it's just a signal numbered 28, which I then found in `signal.h` to be `SIGWINCH`. And only then I understood how I triggered it in the first place (by changing terminal window size).
It'd be much more useful if EDB reported all signals, be it `SIGCHLD`, `SIGUSR1` or whatever, as named signals instead of "debug event-> XX".

**Comment by eteran** [comment]
Yea, the `switch` to report signals is not exhaustive, it mainly covers the ones I've encountered while debugging :-). So when it doesn't know, it just reports the number. It is however a good idea to expand this table to be closer to complete.

**Comment by eteran** [comment]
addressed by most recent commit

**Comment by 10110111** [comment]
This hasn't fixed the `SIGWINCH`. I.e. I still get `debug event-> 28` instead of your message. It's somehow handled in `debug_event_stopped()` instead of `error_description()`. Indeed, it's not an error, just at stop.

**Comment by eteran** [comment]
Fair enough, I will put in some code to handle it in the stop even too :-)
